---
stages:
  - build

workflow:
  image: registry.gitlab.com/renaissance7/s3-backup/docker-compose:latest
  services:
    - docker:dind
  stage: build
  variables:
    TAG: $CI_REGISTRY/renaissance7/s3-backup/backup-media:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --file="$(pwd)/.docker/aws-cli/Dockerfile" --tag ${TAG} .
    - docker push ${TAG}
